- name: Deploy Docker Container
  hosts: websever
  become: true

  tasks:

    - name: login to jfrog
      docker_login:
        registry_url: trialtypobk.jfrog.io
        username: "{{ jfrog_user }}"
        password: "{{ jfrog_pass }}"

    - name: pull an image
      docker_container:
        name: myapp
        image: "{{ image }}"   # ✅ THIS IS THE FIX
        state: started
        recreate: yes
        ports:
          - "8080:8080"
