---
- hosts: websever
  become: yes
  vars:
    build_number: '{{ BUILD_NUMBER }}'
  #become_user: tomcat
  tasks:

  - name: create directory 
    file:
      path: /home/ubuntu/sourcefile
      state: directory
      mode: 0777

  - name: download war file
    ansible.builtin.get_url:
      url: "{{ url_artifact }}"
      dest: /home/ubuntu/sourcefile/webapp.war
      username: test
      password: Test@12345

  - name: create directory for backup
    file: 
      path: /home/ubuntu/backup
      state: directory
      mode: 0777

  - name: backup file with owner and permissions
    copy:
      src: /opt/tomcat/webapps/webappnew.war
      dest: /home/ubuntu/backup/webappnew.war
      remote_src: yes

  - name: Delete remote war file
    file:
      path: /opt/tomcat/webapps/webappnew.war
      state: absent

  - name: deploy file with owner and permissions
    copy:
      src: /home/ubuntu/sourcefile/webapp.war
      dest: /opt/tomcat/webapps/webappnew.war
      remote_src: yes
