---
- hosts: websever
  become: yes

  vars:
    build_number: "{{ BUILD_NUMBER }}"

  tasks:

    - name: create backup directory
      file:
        path: /home/ubuntu/backup
        state: directory
        mode: 0777

    - name: check if existing war exists
      stat:
        path: /opt/tomcat/webapps/webappnew.war
      register: war_file

    - name: backup existing war
      copy:
        src: /opt/tomcat/webapps/webappnew.war
        dest: /home/ubuntu/backup/webappnew.war
        remote_src: yes
      when: war_file.stat.exists

    - name: download new war directly to tomcat
      ansible.builtin.get_url:
        url: "{{ url_artifact }}"
        dest: /opt/tomcat/webapps/webappnew.war
        username: test
        password: Test@12345
        mode: 0644

    - name: restart tomcat
      service:
        name: tomcat
        state: restarted
